package project

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

type DevelopmentIdentity struct {
	Mode                string `json:"mode"`
	Warning             string `json:"warning"`
	ChainID             string `json:"chain_id"`
	ValidatorID         string `json:"validator_id"`
	Moniker             string `json:"moniker"`
	NodeKeySeed         string `json:"node_key_seed"`
	ConsensusKeySeed    string `json:"consensus_key_seed"`
	PeerID              string `json:"peer_id"`
	ConsensusPublicKey  string `json:"consensus_public_key"`
	OperatorAddress     string `json:"operator_address"`
	RewardAddress       string `json:"reward_address"`
}

type NodeInitBundle struct {
	Validator ValidatorPlanOutput `json:"validator"`
	Identity  DevelopmentIdentity `json:"identity"`
	Config    NodeConfigBundle    `json:"config"`
}

type NodeConfigBundle struct {
	NodeHome          string            `json:"node_home"`
	ChainID           string            `json:"chain_id"`
	PersistentPeers   []string          `json:"persistent_peers"`
	RPCListenAddress  string            `json:"rpc_listen_address"`
	P2PListenAddress  string            `json:"p2p_listen_address"`
	AppListenAddress  string            `json:"app_listen_address"`
	PrometheusAddress string            `json:"prometheus_address"`
	Environment       map[string]string `json:"environment"`
}

func DevelopmentIdentityForValidator(bundle Bundle, validatorID string) (DevelopmentIdentity, error) {
	validator, err := validatorByID(bundle, validatorID)
	if err != nil {
		return DevelopmentIdentity{}, err
	}

	return DevelopmentIdentity{
		Mode:               "development_only",
		Warning:            "deterministic placeholder identity for local bootstrap only; do not use for production validator custody",
		ChainID:            bundle.Topology.ChainID,
		ValidatorID:        validator.ID,
		Moniker:            validator.Moniker,
		NodeKeySeed:        digestLabel(bundle.Topology.ChainID, validator.ID, "node-key"),
		ConsensusKeySeed:   digestLabel(bundle.Topology.ChainID, validator.ID, "consensus-key"),
		PeerID:             shortDigest(bundle.Topology.ChainID, validator.ID, "peer-id", 40),
		ConsensusPublicKey: "ed25519:" + shortDigest(bundle.Topology.ChainID, validator.ID, "consensus-pub", 64),
		OperatorAddress:    "0aioper1" + shortDigest(bundle.Topology.ChainID, validator.ID, "operator", 38),
		RewardAddress:      "0aireward1" + shortDigest(bundle.Topology.ChainID, validator.ID, "reward", 38),
	}, nil
}

func NodeInitPlan(bundle Bundle, validatorID string) (NodeInitBundle, error) {
	validator, err := ValidatorPlan(bundle, validatorID)
	if err != nil {
		return NodeInitBundle{}, err
	}
	identity, err := DevelopmentIdentityForValidator(bundle, validatorID)
	if err != nil {
		return NodeInitBundle{}, err
	}

	return NodeInitBundle{
		Validator: validator,
		Identity:  identity,
		Config: NodeConfigBundle{
			NodeHome:          validator.Home,
			ChainID:           bundle.Topology.ChainID,
			PersistentPeers:   validator.PersistentPeers,
			RPCListenAddress:  validator.RPCAddress,
			P2PListenAddress:  validator.P2PAddress,
			AppListenAddress:  validator.AppAddress,
			PrometheusAddress: validator.PrometheusAddress,
			Environment: map[string]string{
				"CHAIN_ID":           bundle.Topology.ChainID,
				"BINARY":             bundle.Topology.Binary,
				"CONTAINER_IMAGE":    bundle.Topology.ContainerImage,
				"VALIDATOR_MONIKER":  validator.Moniker,
				"VALIDATOR_OPERATOR": identity.OperatorAddress,
			},
		},
	}, nil
}

func WriteNodeInitBundle(path string, bundle NodeInitBundle) error {
	root := filepath.Clean(path)
	configDir := filepath.Join(root, "config")

	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return err
	}

	if err := WriteJSON(filepath.Join(root, "manifest.json"), bundle); err != nil {
		return err
	}
	if err := WriteJSON(filepath.Join(configDir, "identity.json"), bundle.Identity); err != nil {
		return err
	}
	if err := WriteJSON(filepath.Join(configDir, "node.json"), bundle.Config); err != nil {
		return err
	}

	return os.WriteFile(
		filepath.Join(root, "README.txt"),
		[]byte("Development-only node bundle generated by 0aid init-node.\nDo not use these placeholder identities in production.\n"),
		0o644,
	)
}

func validatorByID(bundle Bundle, validatorID string) (ValidatorNode, error) {
	for _, validator := range bundle.Topology.Validators {
		if validator.ID == validatorID {
			return validator, nil
		}
	}
	return ValidatorNode{}, fmt.Errorf("unknown validator id: %s", validatorID)
}

func digestLabel(parts ...string) string {
	sum := sha256.Sum256([]byte(joinParts(parts...)))
	return hex.EncodeToString(sum[:])
}

func shortDigest(chainID, validatorID, label string, length int) string {
	value := digestLabel(chainID, validatorID, label)
	if length > len(value) {
		return value
	}
	return value[:length]
}

func joinParts(parts ...string) string {
	return fmt.Sprintf("%s", filepath.ToSlash(filepath.Join(parts...)))
}
